# Generated by Django 5.2.10 on 2026-02-16 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('restaurants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='orders.order')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner_reviews_received', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to='restaurants.restaurant')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='reviews_rating_between_1_and_5'), models.CheckConstraint(condition=models.Q(models.Q(('restaurant__isnull', False), ('partner__isnull', True)), models.Q(('restaurant__isnull', True), ('partner__isnull', False)), _connector='OR'), name='reviews_exactly_one_target'), models.UniqueConstraint(condition=models.Q(('restaurant__isnull', False)), fields=('order', 'customer', 'restaurant'), name='unique_restaurant_review_per_order_customer'), models.UniqueConstraint(condition=models.Q(('partner__isnull', False)), fields=('order', 'customer', 'partner'), name='unique_partner_review_per_order_customer')],
            },
        ),
    ]
